# Generated by Django 4.0.6 on 2023-11-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='presentation_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
