# Generated by Django 4.0.6 on 2023-11-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_test_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tid',
        ),
    ]
