# Generated by Django 4.2.7 on 2023-12-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_course_control_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
