# Generated by Django 4.0.6 on 2023-12-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='position_in_themes_list',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
