# Generated by Django 4.0.6 on 2023-12-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_theme_position_in_themes_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['-position_in_themes_list']},
        ),
    ]
