# Generated by Django 4.0.6 on 2023-12-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_theme_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['position_in_themes_list']},
        ),
    ]
