# Generated by Django 5.0 on 2023-12-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_theme_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("connection_number", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
