# Generated by Django 4.2.6 on 2023-12-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_course_invited_users_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='choose_who_can_view_the_course',
            field=models.BooleanField(default=True),
        ),
    ]
