# Generated by Django 4.2.6 on 2023-12-27 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_course_choose_who_can_view_the_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='invited_users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
