# Generated by Django 4.2.6 on 2024-01-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_theme_description_alter_theme_presentation_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="video_meeting",
            field=models.URLField(blank=True, null=True),
        ),
    ]
