# Generated by Django 4.2.6 on 2024-01-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_theme_video_meeting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="presentation_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
