# Generated by Django 4.2.6 on 2024-01-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_alter_theme_presentation_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
