# Generated by Django 4.2.6 on 2024-01-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_additionalresource_remove_theme_presentation_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalresource",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
