# Generated by Django 4.2.6 on 2024-01-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_alter_additionalresource_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="has_homework",
            field=models.BooleanField(default=False),
        ),
    ]
