# Generated by Django 4.2.6 on 2024-01-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_homework"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeWorkAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attachment", models.FileField(upload_to="uploads")),
            ],
        ),
        migrations.RemoveField(
            model_name="homework",
            name="files",
        ),
        migrations.AddField(
            model_name="homework",
            name="files",
            field=models.ManyToManyField(to="main.homeworkattachment"),
        ),
    ]
