# Generated by Django 4.2.6 on 2024-01-08 19:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_homeworkattachment_remove_homework_files_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homework",
            name="files",
        ),
        migrations.DeleteModel(
            name="HomeWorkAttachment",
        ),
        migrations.AddField(
            model_name="homework",
            name="files",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FileField(upload_to="uploads"), default=[], size=None
            ),
            preserve_default=False,
        ),
    ]
