# Generated by Django 4.2.6 on 2024-01-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0024_attachment_remove_homework_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="attachments",
            field=models.ManyToManyField(to="main.attachment"),
        ),
    ]
