# Generated by Django 4.2.6 on 2024-01-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0026_remove_homework_attachments_delete_attachment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
            ],
        ),
        migrations.RemoveField(
            model_name="homework",
            name="attachments",
        ),
        migrations.AddField(
            model_name="homework",
            name="attachments",
            field=models.ManyToManyField(to="main.attachment"),
        ),
    ]
