# Generated by Django 4.2.6 on 2024-01-19 17:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_homework_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
